import { Demand, Project, CalendarEvent, TeamMember } from '../types';

export const mockDemands: Demand[] = [
  {
    id: '1',
    code: 'DEM-1042',
    title: 'Migração do Servidor de Autenticação OAuth2',
    description: 'Atualizar os serviços legados para a nova infraestrutura de identidade com tokens JWT rotativos.',
    urgency: 'critical',
    impact: 'critical',
    priority_score: 16,
    priority: 'critical',
    status: 'in_progress',
    category: 'Tecnologia',
    system_affected: 'Serviço de SSO Interno',
    requester: 'Jonathan Müller',
    assignee: 'Carlos Eduardo',
    createdAt: '2026-08-10',
    submitted_at: '2026-08-10T09:00:00Z',
    first_response_at: '2026-08-10T09:45:00Z',
    dueDate: '2026-08-18',
  },
  {
    id: '2',
    code: 'DEM-1041',
    title: 'Redesign do Flow de Onboarding da Equipe',
    description: 'Criar wireframes e protótipos interativos no Figma para simplificar a entrada de novos gestores.',
    urgency: 'medium',
    impact: 'high',
    priority_score: 6,
    priority: 'medium',
    status: 'waiting_approval',
    category: 'Marketing',
    channel: 'Portal Interno',
    requester: 'Mariana Souza',
    assignee: 'Ana Beatriz',
    createdAt: '2026-08-08',
    submitted_at: '2026-08-08T10:30:00Z',
    first_response_at: '2026-08-08T11:15:00Z',
    dueDate: '2026-08-15',
  },
  {
    id: '3',
    code: 'DEM-1040',
    title: 'Relatório Consolidado do Q3 / DRE Operacional',
    description: 'Extrair métricas de desempenho e gastos do trimestre para apresentação aos diretores.',
    urgency: 'high',
    impact: 'critical',
    priority_score: 12,
    priority: 'high',
    status: 'new',
    category: 'Financeiro',
    justification: 'Insumo obrigatório para reunião do Conselho Consultivo na próxima semana.',
    requester: 'Roberto Alves',
    assignee: 'Fernanda Lima',
    createdAt: '2026-08-11',
    submitted_at: '2026-08-11T14:00:00Z',
    dueDate: '2026-08-25',
  },
  {
    id: '4',
    code: 'DEM-1039',
    title: 'Implementação de Dashboard de Indicadores em Tempo Real',
    description: 'Conectar métricas de engajamento e SLAs de atendimento em cards responsivos no HubTask.',
    urgency: 'high',
    impact: 'high',
    priority_score: 9,
    priority: 'high',
    status: 'triage',
    category: 'Tecnologia',
    system_affected: 'Módulo Dashboard / Analytics',
    requester: 'Jonathan Müller',
    assignee: 'Lucas Silveira',
    createdAt: '2026-08-05',
    submitted_at: '2026-08-05T08:00:00Z',
    first_response_at: '2026-08-05T09:30:00Z',
    dueDate: '2026-08-20',
  },
  {
    id: '5',
    code: 'DEM-1038',
    title: 'Auditoria de Segurança & Conformidade LGPD',
    description: 'Revisar logs de acesso e políticas de retenção de dados sensíveis dos clientes.',
    urgency: 'low',
    impact: 'medium',
    priority_score: 2,
    priority: 'low',
    status: 'completed',
    category: 'Operacional',
    requester: 'Ana Paula',
    assignee: 'Carlos Eduardo',
    createdAt: '2026-08-01',
    submitted_at: '2026-08-01T11:00:00Z',
    first_response_at: '2026-08-01T11:20:00Z',
    dueDate: '2026-08-09',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    code: 'PRJ-2026-A',
    name: 'Portal do Colaborador 2.0',
    description: 'Plataforma unificada para comunicação interna e gestão de demandas de RH.',
    department: 'Recursos Humanos',
    progress: 78,
    status: 'active',
    priority: 'high',
    assignee: 'Carlos Eduardo',
    manager: 'Jonathan Müller',
    membersCount: 8,
    startDate: '2026-06-01',
    endDate: '2026-09-30',
    baseline: '2026-09-30',
  },
  {
    id: 'p2',
    code: 'PRJ-2026-B',
    name: 'Automação de Pipelines CI/CD',
    description: 'Deploy automatizado e testes contínuos para todos os repositórios corporativos.',
    department: 'Engenharia de Software',
    progress: 92,
    status: 'active',
    priority: 'critical',
    assignee: 'Lucas Silveira',
    manager: 'Carlos Eduardo',
    membersCount: 5,
    startDate: '2026-07-10',
    endDate: '2026-08-31',
    baseline: '2026-08-31',
  },
  {
    id: 'p3',
    code: 'PRJ-2026-C',
    name: 'Reformulação da Marca Institucional',
    description: 'Novo design system, paleta de cores e renovação do portal institucional.',
    department: 'Marketing & Design',
    progress: 45,
    status: 'planning',
    priority: 'medium',
    assignee: 'Ana Beatriz',
    manager: 'Mariana Souza',
    membersCount: 12,
    startDate: '2026-08-15',
    endDate: '2026-11-15',
    baseline: '2026-11-15',
  },
  {
    id: 'p4',
    code: 'PRJ-2026-D',
    name: 'Consolidação do Data Lake Interno',
    description: 'Centralização de dados financeiros e operacionais em banco analítico.',
    department: 'Data & Analytics',
    progress: 100,
    status: 'completed',
    priority: 'low',
    assignee: 'Fernanda Lima',
    manager: 'Jonathan Müller',
    membersCount: 6,
    startDate: '2026-04-01',
    endDate: '2026-08-01',
    baseline: '2026-08-01',
  },
];

export const mockEvents: CalendarEvent[] = [
  {
    id: 'e1',
    title: 'Reunião de Alinhamento Semanal do HubTask',
    description: 'Sincronização de progresso das sprints e análise de impedimentos com a equipe.',
    date: '2026-08-12',
    startTime: '09:00',
    endTime: '10:30',
    time: '09:00 - 10:30',
    type: 'meeting',
    project_id: 'p1',
    location: 'Sala Virtual / Google Meet',
  },
  {
    id: 'e2',
    title: 'Bloco de Foco: Refatoração do Módulo SSO',
    description: 'Tempo focado sem interrupções para desenvolvimento de tokens JWT.',
    date: '2026-08-12',
    startTime: '10:00', // Overlaps 10:00 - 10:30 with e1 (Intentional conflict test)
    endTime: '12:00',
    time: '10:00 - 12:00',
    type: 'focus',
    project_id: 'p2',
    location: 'Bancada Dev',
  },
  {
    id: 'e3',
    title: 'Code Review & Deploy da Sprint #14',
    description: 'Revisão técnica de PRs e validação do pipeline CI/CD.',
    date: '2026-08-12',
    startTime: '14:00',
    endTime: '16:30',
    time: '14:00 - 16:30',
    type: 'project',
    project_id: 'p2',
    location: 'GitHub / Server',
  },
  {
    id: 'e4',
    title: 'Review de UX & Design System',
    description: 'Validação dos componentes visuais com o time de design.',
    date: '2026-08-14',
    startTime: '10:30',
    endTime: '11:30',
    time: '10:30 - 11:30',
    type: 'meeting',
    project_id: 'p3',
    location: 'Sala 03 - Sede Matriz',
  },
  {
    id: 'e5',
    title: 'Elaboração de Relatório de Custos Q3',
    description: 'Consolidação de dados operacionais e financeiros.',
    date: '2026-08-15',
    startTime: '13:00',
    endTime: '16:00',
    time: '13:00 - 16:00',
    type: 'task',
    project_id: 'p4',
    location: 'Estação Financeira',
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm1',
    name: 'Carlos Eduardo',
    role: 'Tech Lead / Arquiteto',
    department: 'Engenharia',
    status: 'online',
    avatar: 'CE',
    email: 'carlos.eduardo@hubtask.com',
    activeTasksCount: 6,
  },
  {
    id: 'tm2',
    name: 'Ana Beatriz',
    role: 'Product Designer Lead',
    department: 'Design',
    status: 'online',
    avatar: 'AB',
    email: 'ana.beatriz@hubtask.com',
    activeTasksCount: 4,
  },
  {
    id: 'tm3',
    name: 'Mariana Souza',
    role: 'Coordenadora de Comunicação',
    department: 'Marketing',
    status: 'busy',
    avatar: 'MS',
    email: 'mariana.souza@hubtask.com',
    activeTasksCount: 3,
  },
  {
    id: 'tm4',
    name: 'Lucas Silveira',
    role: 'Desenvolvedor Full Stack',
    department: 'Engenharia',
    status: 'away',
    avatar: 'LS',
    email: 'lucas.silveira@hubtask.com',
    activeTasksCount: 5,
  },
  {
    id: 'tm5',
    name: 'Fernanda Lima',
    role: 'Analista de Controladoria',
    department: 'Financeiro',
    status: 'offline',
    avatar: 'FL',
    email: 'fernanda.lima@hubtask.com',
    activeTasksCount: 2,
  },
];
